-- Patient Service Tables (pt schema)

USE HealthcarePlatform;
GO

-- Patients Table
CREATE TABLE pt.Patients (
    PatientId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    FirstName NVARCHAR(100) NOT NULL,
    MiddleName NVARCHAR(100),
    LastName NVARCHAR(100) NOT NULL,
    DateOfBirth DATE NOT NULL,
    Gender NVARCHAR(20) NOT NULL,
    SsnEncrypted NVARCHAR(500),
    SsnHash NVARCHAR(128),
    Email NVARCHAR(255) NOT NULL UNIQUE,
    PhoneNumber NVARCHAR(20) NOT NULL,
    AlternatePhone NVARCHAR(20),
    AddressLine1 NVARCHAR(200) NOT NULL,
    AddressLine2 NVARCHAR(200),
    City NVARCHAR(100) NOT NULL,
    State NVARCHAR(2) NOT NULL,
    ZipCode NVARCHAR(10) NOT NULL,
    Country NVARCHAR(50) DEFAULT 'USA',
    Race NVARCHAR(100),
    Ethnicity NVARCHAR(100),
    PreferredLanguage NVARCHAR(50),
    MaritalStatus NVARCHAR(50),
    EmergencyContactName NVARCHAR(200),
    EmergencyContactPhone NVARCHAR(20),
    EmergencyContactRelationship NVARCHAR(50),
    FhirPatientId NVARCHAR(100),
    LastFhirSync DATETIME2,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2,
    CreatedBy NVARCHAR(100) NOT NULL,
    UpdatedBy NVARCHAR(100),
    IsActive BIT DEFAULT 1,
    IsDeleted BIT DEFAULT 0,
    INDEX IX_Email (Email),
    INDEX IX_SsnHash (SsnHash),
    INDEX IX_Name_DOB (LastName, FirstName, DateOfBirth)
);
GO

-- Family Relations Table
CREATE TABLE pt.FamilyRelations (
    RelationId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PatientId UNIQUEIDENTIFIER NOT NULL,
    RelatedPatientId UNIQUEIDENTIFIER NOT NULL,
    RelationType NVARCHAR(50) NOT NULL,
    IsGuardian BIT DEFAULT 0,
    IsProxy BIT DEFAULT 0,
    CanViewRecords BIT DEFAULT 0,
    CanManageRecords BIT DEFAULT 0,
    CanGrantConsent BIT DEFAULT 0,
    LegalDocumentType NVARCHAR(100),
    LegalDocumentNumber NVARCHAR(100),
    LegalDocumentExpiryDate DATETIME2,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2,
    CreatedBy NVARCHAR(100) NOT NULL,
    IsActive BIT DEFAULT 1,
    FOREIGN KEY (PatientId) REFERENCES pt.Patients(PatientId),
    FOREIGN KEY (RelatedPatientId) REFERENCES pt.Patients(PatientId),
    INDEX IX_PatientId (PatientId),
    INDEX IX_RelatedPatientId (RelatedPatientId)
);
GO

-- Allergies Table
CREATE TABLE pt.Allergies (
    AllergyId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PatientId UNIQUEIDENTIFIER NOT NULL,
    AllergenName NVARCHAR(200) NOT NULL,
    AllergenType NVARCHAR(50) NOT NULL,
    AllergenCode NVARCHAR(50),
    CodeSystem NVARCHAR(100),
    Severity NVARCHAR(50) NOT NULL,
    ClinicalStatus NVARCHAR(50) DEFAULT 'Active',
    Reaction NVARCHAR(MAX),
    OnsetDate DATETIME2,
    ReportedBy NVARCHAR(200),
    VerificationStatus NVARCHAR(50),
    FhirAllergyIntoleranceId NVARCHAR(100),
    LastFhirSync DATETIME2,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2,
    CreatedBy NVARCHAR(100) NOT NULL,
    IsActive BIT DEFAULT 1,
    FOREIGN KEY (PatientId) REFERENCES pt.Patients(PatientId) ON DELETE CASCADE,
    INDEX IX_PatientId (PatientId)
);
GO

-- Conditions Table
CREATE TABLE pt.Conditions (
    ConditionId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PatientId UNIQUEIDENTIFIER NOT NULL,
    ConditionName NVARCHAR(300) NOT NULL,
    ConditionCode NVARCHAR(50),
    CodeSystem NVARCHAR(100),
    ClinicalStatus NVARCHAR(50) DEFAULT 'Active',
    VerificationStatus NVARCHAR(50),
    Severity NVARCHAR(50),
    Category NVARCHAR(100),
    OnsetDate DATETIME2,
    AbatementDate DATETIME2,
    RecordedDate DATETIME2,
    Notes NVARCHAR(MAX),
    FhirConditionId NVARCHAR(100),
    LastFhirSync DATETIME2,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2,
    CreatedBy NVARCHAR(100) NOT NULL,
    IsActive BIT DEFAULT 1,
    FOREIGN KEY (PatientId) REFERENCES pt.Patients(PatientId) ON DELETE CASCADE,
    INDEX IX_PatientId (PatientId)
);
GO

-- Immunizations Table
CREATE TABLE pt.Immunizations (
    ImmunizationId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PatientId UNIQUEIDENTIFIER NOT NULL,
    VaccineName NVARCHAR(200) NOT NULL,
    VaccineCode NVARCHAR(50),
    CodeSystem NVARCHAR(100),
    LotNumber NVARCHAR(50),
    ExpirationDate DATETIME2,
    AdministeredDate DATETIME2 NOT NULL,
    AdministeredBy NVARCHAR(200),
    Site NVARCHAR(100),
    Route NVARCHAR(100),
    DoseQuantity NVARCHAR(50),
    DoseNumber INT,
    SeriesDoses INT,
    Status NVARCHAR(50) DEFAULT 'Completed',
    StatusReason NVARCHAR(200),
    ProviderName NVARCHAR(200),
    FacilityName NVARCHAR(200),
    FhirImmunizationId NVARCHAR(100),
    LastFhirSync DATETIME2,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2,
    CreatedBy NVARCHAR(100) NOT NULL,
    IsActive BIT DEFAULT 1,
    FOREIGN KEY (PatientId) REFERENCES pt.Patients(PatientId) ON DELETE CASCADE,
    INDEX IX_PatientId (PatientId)
);
GO

-- Insurance Table
CREATE TABLE pt.Insurances (
    InsuranceId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PatientId UNIQUEIDENTIFIER NOT NULL,
    PayerName NVARCHAR(200) NOT NULL,
    PlanName NVARCHAR(200) NOT NULL,
    PlanType NVARCHAR(50) NOT NULL,
    MemberId NVARCHAR(100) NOT NULL,
    GroupNumber NVARCHAR(100),
    GroupName NVARCHAR(200),
    EffectiveDate DATETIME2 NOT NULL,
    ExpirationDate DATETIME2,
    IsPrimary BIT DEFAULT 1,
    Priority INT DEFAULT 1,
    SubscriberRelationship NVARCHAR(50) DEFAULT 'Self',
    SubscriberName NVARCHAR(200),
    SubscriberDateOfBirth DATETIME2,
    SubscriberSsnEncrypted NVARCHAR(500),
    PayerPhone NVARCHAR(20),
    PayerWebsite NVARCHAR(500),
    CustomerServicePhone NVARCHAR(20),
    Deductible DECIMAL(18,2),
    DeductibleMet DECIMAL(18,2),
    OutOfPocketMax DECIMAL(18,2),
    OutOfPocketMet DECIMAL(18,2),
    Copay DECIMAL(18,2),
    CoinsurancePercentage DECIMAL(5,2),
    Status NVARCHAR(50) DEFAULT 'Active',
    IsVerified BIT DEFAULT 0,
    LastVerifiedDate DATETIME2,
    FhirCoverageId NVARCHAR(100),
    LastFhirSync DATETIME2,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2,
    CreatedBy NVARCHAR(100) NOT NULL,
    IsActive BIT DEFAULT 1,
    FOREIGN KEY (PatientId) REFERENCES pt.Patients(PatientId) ON DELETE CASCADE,
    INDEX IX_PatientId (PatientId),
    INDEX IX_MemberId (MemberId)
);
GO

-- Consents Table
CREATE TABLE pt.Consents (
    ConsentId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PatientId UNIQUEIDENTIFIER NOT NULL,
    ConsentType NVARCHAR(100) NOT NULL,
    Status NVARCHAR(50) DEFAULT 'Active',
    Scope NVARCHAR(100) NOT NULL,
    AllowDemographics BIT DEFAULT 0,
    AllowAllergies BIT DEFAULT 0,
    AllowConditions BIT DEFAULT 0,
    AllowImmunizations BIT DEFAULT 0,
    AllowMedications BIT DEFAULT 0,
    AllowInsurance BIT DEFAULT 0,
    AllowDocuments BIT DEFAULT 0,
    AllowEncounters BIT DEFAULT 0,
    RecipientName NVARCHAR(200),
    RecipientOrganization NVARCHAR(200),
    RecipientType NVARCHAR(100),
    RecipientEmail NVARCHAR(255),
    ShareToken NVARCHAR(200) UNIQUE,
    TokenExpiryDate DATETIME2,
    MaxAccessCount INT,
    AccessCount INT DEFAULT 0,
    GrantedDate DATETIME2 DEFAULT GETUTCDATE(),
    ExpiryDate DATETIME2,
    RevokedDate DATETIME2,
    RevocationReason NVARCHAR(500),
    LegalBasis NVARCHAR(200),
    ConsentFormUrl NVARCHAR(500),
    SignatureObtained BIT DEFAULT 0,
    SignatureDate DATETIME2,
    Purpose NVARCHAR(500),
    Notes NVARCHAR(MAX),
    LastAccessedBy NVARCHAR(200),
    LastAccessedAt DATETIME2,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2,
    CreatedBy NVARCHAR(100) NOT NULL,
    UpdatedBy NVARCHAR(100),
    FOREIGN KEY (PatientId) REFERENCES pt.Patients(PatientId) ON DELETE CASCADE,
    INDEX IX_PatientId (PatientId),
    INDEX IX_ShareToken (ShareToken)
);
GO

-- Consent Audits Table
CREATE TABLE pt.ConsentAudits (
    AuditId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ConsentId UNIQUEIDENTIFIER NOT NULL,
    Action NVARCHAR(100) NOT NULL,
    ActionDetails NVARCHAR(MAX),
    ActionDate DATETIME2 DEFAULT GETUTCDATE(),
    ActorId NVARCHAR(100) NOT NULL,
    ActorName NVARCHAR(200) NOT NULL,
    ActorRole NVARCHAR(100),
    ActorOrganization NVARCHAR(200),
    IpAddress NVARCHAR(50),
    UserAgent NVARCHAR(500),
    SessionId NVARCHAR(100),
    DataTypesAccessed NVARCHAR(MAX),
    ResourcesAccessed NVARCHAR(MAX),
    FOREIGN KEY (ConsentId) REFERENCES pt.Consents(ConsentId) ON DELETE CASCADE,
    INDEX IX_ConsentId (ConsentId),
    INDEX IX_ActionDate (ActionDate)
);
GO

-- Encounters Table
CREATE TABLE pt.Encounters (
    EncounterId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PatientId UNIQUEIDENTIFIER NOT NULL,
    EncounterType NVARCHAR(100) NOT NULL,
    EncounterClass NVARCHAR(50),
    Status NVARCHAR(50) DEFAULT 'Planned',
    PlannedStartDate DATETIME2,
    ActualStartDate DATETIME2,
    EndDate DATETIME2,
    DurationMinutes INT,
    ProviderId NVARCHAR(100),
    ProviderName NVARCHAR(200),
    ProviderSpecialty NVARCHAR(100),
    ProviderNpi NVARCHAR(20),
    FacilityId NVARCHAR(100),
    FacilityName NVARCHAR(200),
    Department NVARCHAR(100),
    Room NVARCHAR(50),
    ChiefComplaint NVARCHAR(500),
    ReasonForVisit NVARCHAR(500),
    ReasonCode NVARCHAR(50),
    Priority NVARCHAR(50),
    PrimaryDiagnosisCode NVARCHAR(50),
    PrimaryDiagnosisDescription NVARCHAR(500),
    SecondaryDiagnoses NVARCHAR(MAX),
    DischargeDisposition NVARCHAR(100),
    DischargeInstructions NVARCHAR(MAX),
    BillingCode NVARCHAR(50),
    EstimatedCost DECIMAL(18,2),
    ClinicalNotes NVARCHAR(MAX),
    FhirEncounterId NVARCHAR(100),
    LastFhirSync DATETIME2,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2,
    CreatedBy NVARCHAR(100) NOT NULL,
    IsActive BIT DEFAULT 1,
    FOREIGN KEY (PatientId) REFERENCES pt.Patients(PatientId) ON DELETE CASCADE,
    INDEX IX_PatientId (PatientId),
    INDEX IX_ActualStartDate (ActualStartDate)
);
GO

-- Documents Table
CREATE TABLE pt.Documents (
    DocumentId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PatientId UNIQUEIDENTIFIER NOT NULL,
    EncounterId UNIQUEIDENTIFIER,
    FileName NVARCHAR(500) NOT NULL,
    DocumentType NVARCHAR(100) NOT NULL,
    DocumentTypeCode NVARCHAR(50),
    ContentType NVARCHAR(100) NOT NULL,
    FileSize BIGINT NOT NULL,
    StorageLocation NVARCHAR(1000) NOT NULL,
    EncryptionKeyId NVARCHAR(100),
    FileHash NVARCHAR(256),
    Category NVARCHAR(100),
    Specialty NVARCHAR(100),
    FacilityType NVARCHAR(100),
    ProviderId NVARCHAR(100),
    ProviderName NVARCHAR(200),
    ServiceDate DATETIME2,
    OcrProcessed BIT DEFAULT 0,
    OcrProcessedDate DATETIME2,
    OcrText NVARCHAR(MAX),
    OcrConfidence NVARCHAR(50),
    FhirMapped BIT DEFAULT 0,
    FhirMappingResult NVARCHAR(MAX),
    Status NVARCHAR(50) DEFAULT 'Current',
    Description NVARCHAR(500),
    SecurityLevel NVARCHAR(50) DEFAULT 'Standard',
    RequiresConsent BIT DEFAULT 1,
    FhirDocumentReferenceId NVARCHAR(100),
    LastFhirSync DATETIME2,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2,
    CreatedBy NVARCHAR(100) NOT NULL,
    IsActive BIT DEFAULT 1,
    FOREIGN KEY (PatientId) REFERENCES pt.Patients(PatientId) ON DELETE CASCADE,
    FOREIGN KEY (EncounterId) REFERENCES pt.Encounters(EncounterId),
    INDEX IX_PatientId (PatientId),
    INDEX IX_EncounterId (EncounterId)
);
GO

-- Record Transfers Table
CREATE TABLE pt.RecordTransfers (
    TransferId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PatientId UNIQUEIDENTIFIER NOT NULL,
    ConsentId UNIQUEIDENTIFIER,
    TransferType NVARCHAR(50) NOT NULL,
    TransferMethod NVARCHAR(50) NOT NULL,
    RecipientOrganization NVARCHAR(200),
    RecipientName NVARCHAR(200),
    RecipientEmail NVARCHAR(255),
    RecipientFhirEndpoint NVARCHAR(500),
    RecipientNpi NVARCHAR(20),
    SenderOrganization NVARCHAR(200),
    SenderName NVARCHAR(200),
    SenderEmail NVARCHAR(255),
    Purpose NVARCHAR(500),
    RequestedBy NVARCHAR(200),
    RequestedDate DATETIME2 DEFAULT GETUTCDATE(),
    Status NVARCHAR(50) DEFAULT 'Requested',
    StatusReason NVARCHAR(500),
    ApprovedDate DATETIME2,
    ApprovedBy NVARCHAR(200),
    CompletedDate DATETIME2,
    CancelledDate DATETIME2,
    CancellationReason NVARCHAR(500),
    IncludeDemographics BIT DEFAULT 1,
    IncludeAllergies BIT DEFAULT 1,
    IncludeConditions BIT DEFAULT 1,
    IncludeImmunizations BIT DEFAULT 1,
    IncludeMedications BIT DEFAULT 1,
    IncludeEncounters BIT DEFAULT 1,
    IncludeDocuments BIT DEFAULT 1,
    IncludeInsurance BIT DEFAULT 0,
    DataStartDate DATETIME2,
    DataEndDate DATETIME2,
    FhirBundleUrl NVARCHAR(1000),
    FhirBundleId NVARCHAR(100),
    ResourceCount INT,
    AccessToken NVARCHAR(500),
    TokenExpiryDate DATETIME2,
    EncryptionKeyId NVARCHAR(100),
    TrackingNumber NVARCHAR(50) UNIQUE,
    ExternalTransferId NVARCHAR(100),
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2,
    CreatedBy NVARCHAR(100) NOT NULL,
    FOREIGN KEY (PatientId) REFERENCES pt.Patients(PatientId) ON DELETE CASCADE,
    FOREIGN KEY (ConsentId) REFERENCES pt.Consents(ConsentId),
    INDEX IX_PatientId (PatientId),
    INDEX IX_TrackingNumber (TrackingNumber)
);
GO

-- Transfer Audits Table
CREATE TABLE pt.TransferAudits (
    AuditId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TransferId UNIQUEIDENTIFIER NOT NULL,
    Action NVARCHAR(100) NOT NULL,
    ActionDetails NVARCHAR(MAX),
    ActionDate DATETIME2 DEFAULT GETUTCDATE(),
    ActorId NVARCHAR(100),
    ActorName NVARCHAR(200),
    ActorRole NVARCHAR(100),
    IpAddress NVARCHAR(50),
    SessionId NVARCHAR(100),
    ErrorMessage NVARCHAR(MAX),
    StackTrace NVARCHAR(MAX),
    FOREIGN KEY (TransferId) REFERENCES pt.RecordTransfers(TransferId) ON DELETE CASCADE,
    INDEX IX_TransferId (TransferId)
);
GO

-- Notifications Table
CREATE TABLE pt.Notifications (
    NotificationId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PatientId UNIQUEIDENTIFIER NOT NULL,
    NotificationType NVARCHAR(50) NOT NULL,
    Category NVARCHAR(100) NOT NULL,
    Title NVARCHAR(500) NOT NULL,
    Message NVARCHAR(MAX) NOT NULL,
    ActionUrl NVARCHAR(500),
    ActionLabel NVARCHAR(100),
    Priority NVARCHAR(50) DEFAULT 'Normal',
    IsRead BIT DEFAULT 0,
    ReadAt DATETIME2,
    IsArchived BIT DEFAULT 0,
    ArchivedAt DATETIME2,
    SendEmail BIT DEFAULT 0,
    EmailSent BIT DEFAULT 0,
    EmailSentAt DATETIME2,
    SendSms BIT DEFAULT 0,
    SmsSent BIT DEFAULT 0,
    SmsSentAt DATETIME2,
    ScheduledFor DATETIME2,
    ExpiresAt DATETIME2,
    RelatedEntityType NVARCHAR(100),
    RelatedEntityId UNIQUEIDENTIFIER,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    CreatedBy NVARCHAR(100) NOT NULL,
    FOREIGN KEY (PatientId) REFERENCES pt.Patients(PatientId) ON DELETE CASCADE,
    INDEX IX_PatientId_IsRead (PatientId, IsRead)
);
GO

-- Audit Logs Table
CREATE TABLE pt.AuditLogs (
    AuditLogId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PatientId UNIQUEIDENTIFIER,
    EventType NVARCHAR(100) NOT NULL,
    EntityType NVARCHAR(100) NOT NULL,
    EntityId UNIQUEIDENTIFIER,
    EventTimestamp DATETIME2 DEFAULT GETUTCDATE(),
    ActorId NVARCHAR(100) NOT NULL,
    ActorName NVARCHAR(200) NOT NULL,
    ActorRole NVARCHAR(100),
    ActorEmail NVARCHAR(255),
    Action NVARCHAR(200) NOT NULL,
    ActionDescription NVARCHAR(MAX),
    OldValues NVARCHAR(MAX),
    NewValues NVARCHAR(MAX),
    IpAddress NVARCHAR(50),
    UserAgent NVARCHAR(500),
    SessionId NVARCHAR(100),
    RequestId NVARCHAR(100),
    CorrelationId NVARCHAR(100),
    Success BIT DEFAULT 1,
    ErrorMessage NVARCHAR(MAX),
    ResponseCode INT,
    AccessReason NVARCHAR(500),
    ConsentId NVARCHAR(100),
    PhiAccessed BIT DEFAULT 0,
    DataClassification NVARCHAR(50),
    ApplicationName NVARCHAR(100),
    Environment NVARCHAR(50),
    FOREIGN KEY (PatientId) REFERENCES pt.Patients(PatientId),
    INDEX IX_PatientId (PatientId),
    INDEX IX_EventTimestamp (EventTimestamp),
    INDEX IX_EventType_EntityType (EventType, EntityType)
);
GO

-- Insurance Documents Table
CREATE TABLE pt.InsuranceDocuments (
    InsuranceDocumentId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    InsuranceId UNIQUEIDENTIFIER NOT NULL,
    FileName NVARCHAR(500) NOT NULL,
    DocumentType NVARCHAR(100) NOT NULL,
    ContentType NVARCHAR(100) NOT NULL,
    FileSize BIGINT NOT NULL,
    StorageLocation NVARCHAR(1000) NOT NULL,
    EncryptionKeyId NVARCHAR(100),
    FileHash NVARCHAR(256),
    EffectiveDate DATETIME2,
    ExpirationDate DATETIME2,
    IsActive BIT DEFAULT 1,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    CreatedBy NVARCHAR(100) NOT NULL,
    FOREIGN KEY (InsuranceId) REFERENCES pt.Insurances(InsuranceId) ON DELETE CASCADE,
    INDEX IX_InsuranceId (InsuranceId)
);
GO

PRINT 'Patient Service tables created successfully';

